repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.9
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-openmmlab
          - mdformat_frontmatter
          - linkify-it-py
  - repo: https://github.com/myint/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "79"]
  # temporarily remove update-model-index to avoid conflict raised
  # by depth estimator models
  # - repo: local
  #   hooks:
  #     - id: update-model-index
  #       name: update-model-index
  #       description: Collect model information and update model-index.yml
  #       entry: .dev_scripts/update_model_index.py
  #       additional_dependencies: [pyyaml]
  #       language: python
  #       require_serial: true
  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v3.0.0
  #   hooks:
  #     - id: pyupgrade
  #       args: ["--py310-plus"]
  - repo: https://github.com/vbti-development/pre-commit-hooks
    rev: 0.4.1  # Use the rev to fix revision
    hooks:
      - id: check-algo-readme
      - id: check-copyright
        args: ["mmseg", "tools", "tests", "demo"]  # the dir_to_check with expected directory to check
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.5
    hooks:
      - id: uv-lock
